services:
  db:
    image: postgres:16
    container_name: clube_leitura_db
    environment:
      POSTGRES_DB: clube
      POSTGRES_USER: clube
      POSTGRES_PASSWORD: clube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clube -d clube"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    image: guilhermesenko/clubeleitura_backend_t2:latest
    container_name: clube_leitura_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: clube
      DB_USER: clube
      DB_PASSWORD: clube
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
