# Generated by Django 6.0.6 on 2026-06-26 00:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quero_ler', 'Quero Ler'), ('lendo', 'Lendo'), ('li', 'Li')], max_length=10)),
                ('nota', models.IntegerField(blank=True, help_text='Nota de 1 a 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resenha', models.TextField(blank=True, help_text='Sua resenha do livro')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='livros.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_adicionado'],
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
